ALTER TABLE user ADD INDEX (user_id, mail, password, employee_id, office_id);
ALTER TABLE department ADD INDEX (department_name, department_id);
ALTER TABLE match_group_member ADD INDEX (user_id, match_group_id);
ALTER TABLE match_group ADD INDEX (match_group_id);
ALTER TABLE department_role_member ADD INDEX (department_id, role_id, user_id);
-- CREATE INDEX idx_user_id ON user (user_id);
-- CREATE INDEX idx_mail ON user (mail);
-- CREATE INDEX idx_password ON user (password);
-- CREATE INDEX idx_employee_id ON user (employee_id);
-- CREATE INDEX idx_office_id ON user (office_id);
-- CREATE INDEX idx_department_name ON department (department_name);
-- CREATE INDEX idx_department_id ON department (department_id);
-- CREATE INDEX idx_user_id ON match_group_member (user_id);
-- CREATE INDEX idx_match_group_id ON match_group_member (match_group_id);
-- CREATE INDEX idx_department_id ON department_role_member (department_id);
-- CREATE INDEX idx_role_id ON department_role_member (role_id);
-- CREATE INDEX idx_user_id ON department_role_member (user_id);
